#!/bin/bash

#SBATCH --job-name=digan

## 4GB memory
#SBATCH --mem=4000


## processes
#SBATCH --ntasks=1

#SBATCH --ntasks-per-node=1

##no. cores
#SBTACH --cpus-per-task=1

##no. gpus
#SBATCH --gres=gpu:3g.40gb:1
#SBATCH --partition=gpu.large

module load python/3.9 cuda/cudnn/8.4.1 
HYDRA_FULL_ERROR=1 CXX=g++ python digan/src/infra/launch.py hydra.run.dir=. +experiment_name=UCF-101 +dataset.name=UCF-101

exit 0